name: "dockerhub-CI-CD"

on:
  push:
    branches:
      - master

env:
  HASH: ${{ github.sha }}

jobs:
  my-testing-docker:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "docker login"
        run: docker login -u sivin79 -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Build"
        run: docker build -t sivin79/hello-world:${{env.HASH}} -t sivin79/hello-world:${{env.HASH}} .

      - name: "Push"
        run: docker push sivin79/hello-world:${{env.HASH}}
