name: "dockerhub-CI-CD"

on:
  release:
    types: [published]
  # Запуск только при публиковании нового релиза

env:
  TAG: "latest"

jobs:
  my-testing-docker:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "docker login"
        run: docker login -u sivin79 -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Build"
        run: docker build -t sivin79/hello_world:${{env.TAG}} -t sivin79/hello_world:${{env.TAG}} .

      - name: "Push"
        run: docker push sivin79/hello_world:${{env.TAG}}
