name: "dockerhub-CI-CD"

on:
  push:
    branches:
      - main

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello message
        run: echo "Hello, world!"

      - name: Show folders
        run: ls -l

      - name: Show terraform version
        run: terraform --version

      - name: Show SHA
        run: echo "app-ver = ${{ env.APP_TAG }}"

  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]

    steps:
      - name: Print Deploy
        run: echo "Hello, world from DEploy!"
# jobs:
#   my-testing-docker:
#     runs-on: ubuntu-latest

#     steps:
#       - name: "Checkout"
#         uses: actions/checkout@main

#       - name: "docker login"
#         run: docker login -u sivin79 -p ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: "Build"
#         run: docker build -t sivin79/hello-world:1.0.1 -t sivin79/hello-world:1.1.1 .

#       - name: "Push"
#         run: docker push sivin79/hello-world:1.1.1
