name: dockerhub-CI-CD

on:
 push:
   branches: 
     - master


jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello message
        run: echo "Hello, world!"

      - name: Show folders
        run: ls -l

      - name: Show terraform version
        run: terraform --version
