name: "dockerhub-CI-CD"

on:
  push:
    branches:
      - main
jobs:
  DOS:
    name: running job
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "docker login"
        run: docker login -u sivin79 -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Build"
        run: docker build -t sivin79/hello-world:1.0.1 -t sivin79/hello-world:1.1.1 .

      - name: "Push"
        run: docker push sivin79/hello-world:1.1.1
